import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import GlobalContext from './context/GlobalContext'
import Msg from './components/Msg'
import Navbar from './components/Navbar'
import Popup from './components/Popup'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="bg-bg">
      <body className="relative">
        <GlobalContext>
          <Popup />
          <Msg />
          <Navbar />
          <main className="custom-container">{children}</main>
        </GlobalContext>
      </body>
    </html>
  );
}
